import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Button } from '@/components/ui/button';
import '../styles/globals.css';
import Link from 'next/link';
// import 'react-day-picker/style.css';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="{inter.className} bg-[var(--background)] text-[var(--foreground)]">
        <div className="container ">
          <header
            // style={{ fontFamily: 'KccAnchangho' }}
            className="text-xl  p-5 box-border flex justify-between"
          >
            <h1 className=" text-2xl">
              <Link href="/">문학의 정원</Link>
            </h1>
            <menu className="flex justify-between  gap-10">
              <Link href="/About">
                <li>모임소개</li>
              </Link>
              <Link href="/Writings">
                <li>글 마당</li>
              </Link>
              <Link href="/BookClub">
                <li>독서/토론</li>
              </Link>
              <Link href="/Gallery">
                <li>갤러리</li>
              </Link>
              <Link href="/Notice">
                <li>공지사항</li>
              </Link>
            </menu>
            <Button>
              <Link href="/login">로그인</Link>
            </Button>
          </header>

          {children}
        </div>
      </body>
    </html>
  );
}
