import '@/src/app/styles/globals.css';
import type { Metadata } from 'next';

import { kccAnchangho } from './font';
import { ThemeProvider } from 'next-themes';
import Header from '../shared/Header';
import Image from 'next/image';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={kccAnchangho.className} suppressHydrationWarning>
      <body className="relative h-screen w-screen overflow-x-hidden">
        <div className="fixed inset-0 -z-10 opacity-10">
          <Image
            src="/background02.jpeg"
            alt="메인 배경 이미지"
            fill
            className="object-cover object-top"
            priority
          />
        </div>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="max-w-5xl m-auto relative z-10">
            <Header />
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
